---
channelname: "ramen-gitops"
channelnamespace: "ramen-samples"
giturl: "https://github.com/RamenDR/ocm-ramen-samples.git"
pvcspecs:
  - storageclassname: rook-cephfs
    accessmodes: ReadWriteMany
  - storageclassname: rook-ceph-block
    accessmodes: ReadWriteOnce
Clusters:
  hub:
    kubeconfigpath: /Users/rtalur/.config/drenv/rdr/kubeconfigs/hub
  c1:
    kubeconfigpath: /Users/rtalur/.config/drenv/rdr/kubeconfigs/dr1
  c2:
    kubeconfigpath: /Users/rtalur/.config/drenv/rdr/kubeconfigs/dr2
