// SPDX-FileCopyrightText: The RamenDR authors
// SPDX-License-Identifier: Apache-2.0

//go:build mage

package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

func run(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

const (
	// addonsSrcDir is the source of the addon kustomizations, relative to this
	// module root. When drenv-go moves to its own repo this becomes the path to
	// wherever the addon overlays are vendored; only Render (build/maintenance
	// time) reads it — the runtime binary does not.
	addonsSrcDir = "../drenv/addons"
	// manifestsDir holds the pre-rendered manifests embedded into the binary.
	manifestsDir = "internal/addon/manifests"
)

// renderTargets maps an addon kustomization directory (relative to addonsSrcDir)
// to the embedded manifest file it renders into. These are the plain
// `kubectl apply -k` addons that fetch upstream bases over the network (rook,
// argocd, olm, csi-addons, external-snapshotter, ocm-controller, recipe).
// Rendering them at build time freezes the upstream content (pinning the
// branch/`main` refs to a snapshot) so runtime apply needs no network.
var renderTargets = map[string]string{
	"rook/cluster":                               "rook-cluster.yaml",
	"rook/operator/start-data/deps":              "rook-operator-deps.yaml",
	"rook/operator/start-data/operator":          "rook-operator.yaml",
	"rook/toolbox":                               "rook-toolbox.yaml",
	"argocd/start-data":                          "argocd.yaml",
	"olm/start-data/crds":                        "olm-crds.yaml",
	"olm/start-data/operators":                   "olm-operators.yaml",
	"csi_addons/start-data":                      "csi-addons.yaml",
	"external_snapshotter/start-data/crds":       "external-snapshotter-crds.yaml",
	"external_snapshotter/start-data/controller": "external-snapshotter-controller.yaml",
	"ocm/controller/start-data":                  "ocm-controller.yaml",
	"recipe/start-data":                          "recipe.yaml",
}

// Render pre-renders the addon kustomizations into standalone manifests under
// internal/addon/manifests, which are then embedded into the binary. It fetches
// the remote bases via the pinned kustomize tool, so it needs network access.
// Run it (make render) to refresh the pinned upstream snapshots; the outputs are
// committed so ordinary builds are hermetic.
func Render() error {
	if err := os.MkdirAll(manifestsDir, 0o755); err != nil {
		return err
	}
	// Deterministic order for readable output and stable diffs.
	dirs := make([]string, 0, len(renderTargets))
	for dir := range renderTargets {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)

	for _, dir := range dirs {
		out := renderTargets[dir]
		src := filepath.Join(addonsSrcDir, dir)
		dst := filepath.Join(manifestsDir, out)
		fmt.Printf("render %s -> %s\n", src, dst)

		cmd := exec.Command("go", "tool", "-modfile=tools.mod", "kustomize", "build", src)
		var stdout bytes.Buffer
		cmd.Stdout = &stdout
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("kustomize build %s: %w", src, err)
		}

		header := fmt.Sprintf("# SPDX-FileCopyrightText: The RamenDR authors\n"+
			"# SPDX-License-Identifier: Apache-2.0\n"+
			"#\n"+
			"# Code generated by `make render` from %s (kustomize build). DO NOT EDIT.\n"+
			"# Re-run `make render` to refresh the pinned upstream snapshot.\n", dir)
		if err := os.WriteFile(dst, append([]byte(header), stdout.Bytes()...), 0o644); err != nil {
			return err
		}
	}
	return nil
}

// Build compiles the drenv-go binary into bin/drenv-go.
func Build() error {
	return run("go", "build", "-o", "bin/drenv-go", "./cmd/drenv-go")
}

// Test runs the unit tests.
func Test() error {
	return run("go", "test", "./...")
}

// Lint runs gofmt and go vet.
func Lint() error {
	out, err := exec.Command("gofmt", "-l", ".").Output()
	if err != nil {
		return err
	}
	if files := strings.TrimSpace(string(out)); files != "" {
		return fmt.Errorf("gofmt found unformatted files:\n%s", files)
	}
	return run("go", "vet", "./...")
}

// Clean removes build artifacts.
func Clean() error {
	return os.RemoveAll("bin")
}
